import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "vi" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  tNav: (viText: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    "login.welcome": "Chào mừng trở lại",
    "login.subtitle": "Đăng nhập vào hệ thống quản lý giáo dục EduManage",
    "login.username": "Tài khoản",
    "login.password": "Mật khẩu",
    "login.forgot": "Quên mật khẩu?",
    "login.submit": "Đăng nhập",
    "login.loading": "Đang đăng nhập...",
    "login.footer": "Hệ thống quản lý giáo dục",
    "login.cover.title": "Tối ưu hoá vận hành",
    "login.cover.desc": "Giải pháp toàn diện giúp quản lý trung tâm giáo dục, theo dõi học viên, lớp học và tài chính trong một nền tảng duy nhất, hiệu quả và thông minh.",
    "notification.title": "Thông báo",
    "notification.markAll": "Đọc tất cả",
    "notification.loading": "Đang tải...",
    "notification.empty": "Không có thông báo",
    "notification.viewDetail": "Xem chi tiết →",
    "notification.collapse": "Thu gọn",
    "notification.expand": "Xem thêm",
    "sidebar.logout": "Đăng xuất",
    "sidebar.system": "Hệ thống",
    "sidebar.location": "Cơ sở:",
    "sidebar.allLocations": "Tất cả cơ sở",
    // Customers page
    "customers.statTotal": "Tổng",
    "customers.statActive": "Đang học",
    "customers.statNoSchedule": "Chưa có lịch",
    "customers.statDeferred": "Bảo lưu",
    "customers.statInactive": "Đã nghỉ",
    "customers.addStudent": "Thêm học viên",
    "customers.searchPlaceholder": "Tìm theo Tên, Mã HV...",
    "customers.upload": "Upload",
    "customers.download": "Download",
    "customers.columns": "Cột",
    "customers.columnSettings": "Cài đặt cột",
    "customers.columnDragHint": "Kéo để sắp xếp",
    "customers.searchColumns": "Tìm cột...",
    "customers.actions": "Thao tác",
    "customers.actionsCount": "Thao tác ({{n}})",
    "customers.bulkActions": "Thao tác hàng loạt",
    "customers.bulkRelationship": "Mối quan hệ",
    "customers.bulkBranch": "Phân cơ sở",
    "customers.bulkSale": "Phân sale",
    "customers.bulkManager": "Phân quản lý",
    "customers.bulkTeacher": "Phân giáo viên",
    "customers.bulkParent": "Phân phụ huynh",
    "customers.bulkClass": "Phân lớp học",
    "customers.bulkAccountStatus": "Trạng thái tài khoản",
    "customers.bulkDelete": "Xóa {{n}} học viên",
    "customers.selectToAction": "Chọn học viên để thực hiện thao tác",
    "customers.filter": "Bộ lọc",
    "customers.filterAdvanced": "Bộ lọc nâng cao",
    "customers.filterApplied": "Đang áp dụng bộ lọc",
    "customers.filterClearAll": "Xoá tất cả",
    "customers.filterBranch": "Cơ sở",
    "customers.filterType": "Phân loại",
    "customers.filterSource": "Nguồn",
    "customers.filterRejectReason": "Lý do từ chối",
    "customers.filterSale": "Sale",
    "customers.filterManager": "Quản lý",
    "customers.filterTeacher": "Giáo viên",
    "customers.filterClass": "Lớp",
    "customers.filterSchool": "Trường học",
    "customers.filterBirthYear": "Năm sinh",
    "customers.filterCreatedFrom": "Ngày tạo",
    "customers.filterTo": "Đến",
    "customers.filterUpdatedFrom": "Ngày cập nhật",
    "customers.filterAccountStatus": "Trạng thái tài khoản",
    "customers.filterStudentStatus": "Trạng thái học viên",
    "customers.filterBirthdayFrom": "Sinh nhật từ",
    "customers.allBranches": "Tất cả cơ sở",
    "customers.allTypes": "Tất cả phân loại",
    "customers.typeStudent": "Học viên",
    "customers.typeParent": "Phụ huynh",
    "customers.selectSource": "Chọn nguồn",
    "customers.selectReason": "Chọn lý do",
    "customers.selectSale": "Chọn sale",
    "customers.selectManager": "Chọn quản lý",
    "customers.selectTeacher": "Chọn giáo viên",
    "customers.selectClass": "Chọn lớp",
    "customers.selectSchool": "Chọn trường",
    "customers.selectBirthYear": "Chọn năm sinh",
    "customers.selectStatus": "Chọn trạng thái",
    "customers.selectDay": "Ngày",
    "customers.selectMonth": "Tháng",
    "customers.statusActive": "Hoạt động",
    "customers.statusInactive": "Không hoạt động",
    "customers.statusLearning": "Đang học",
    "customers.statusWaiting": "Chờ đến lịch",
    "customers.statusDeferred": "Bảo lưu",
    "customers.statusDropped": "Đã nghỉ",
    "customers.statusNoSchedule": "Chưa có lịch",
    "customers.filterAll": "Tất cả",
    "customers.showing": "Hiển thị",
    "customers.of": "/",
    "customers.results": "kết quả",
    "customers.rowsPerPage": "Số hàng:",
    "customers.addDialogTitle": "Thêm Học Viên Mới",
    "customers.addDialogDesc": "Điền đầy đủ thông tin bên dưới để tạo hồ sơ học viên mới.",
    "customers.editDialogTitle": "Chỉnh Sửa Học Viên",
    "customers.editDialogDesc": "Cập nhật thông tin hồ sơ học viên.",
    "customers.activityLog": "Nhật ký",
    "customers.confirmDelete": "Bạn có chắc chắn muốn xóa học viên này?",
    "customers.toastCreated": "Đã thêm học viên mới.",
    "customers.toastUpdated": "Đã cập nhật thông tin học viên.",
    "customers.toastUpdateError": "Không thể cập nhật thông tin học viên.",
    "customers.toastDeleted": "Đã xóa học viên.",
    "customers.toastDeleteError": "Không thể xóa học viên.",
    "customers.toastRelUpdated": "Đã cập nhật mối quan hệ.",
    "customers.toastRelError": "Không thể cập nhật mối quan hệ.",
    "customers.toastStatusUpdated": "Đã cập nhật trạng thái tài khoản.",
    "customers.toastStatusError": "Không thể cập nhật trạng thái.",
    "common.success": "Thành công",
    "common.error": "Lỗi",
    "header.search": "Tìm kiếm...",
    "header.selectBranch": "Chọn cơ sở",
    // Import dialog
    "import.title": "Nhập danh sách học viên",
    "import.titleResult": "Kết quả nhập liệu",
    "import.subtitle": "Tải lên file .xlsx để nhập nhanh vào hệ thống.",
    "import.subtitleResult": "Hệ thống đã xử lý xong file Excel của bạn.",
    "import.successCount": "Nhập thành công",
    "import.errorCount": "Dòng bị lỗi",
    "import.errorDetail": "Chi tiết các dòng lỗi",
    "import.rows": "dòng",
    "import.row": "Dòng",
    "import.errorInfo": "Tải về file lỗi để xem các ô được highlight đỏ kèm lý do, chỉnh sửa rồi import lại.",
    "import.downloadErrors": "Tải file lỗi ({{n}} dòng)",
    "import.importAgain": "Nhập lại",
    "import.close": "Đóng",
    "import.template": "Tải file mẫu Excel",
    "import.templateSub": "Xem định dạng chuẩn trước khi nhập",
    "import.notice": "Lưu ý định dạng file:",
    "import.noticeCol": "Cột B, D, N là bắt buộc",
    "import.noticeCode": "Mã số trống → Tự động (HV-01...)",
    "import.noticeDropdown": "Sử dụng dropdown có sẵn trong file Excel",
    "import.location": "Cơ sở",
    "import.locationOptional": "(tùy chọn)",
    "import.locationPlaceholder": "Chọn cơ sở",
    "import.allowDupePhone": "Cho phép trùng SĐT",
    "import.allowDupePhoneSub": "Bỏ qua kiểm tra trùng số điện thoại",
    "import.allowDupeEmail": "Cho phép trùng Email",
    "import.allowDupeEmailSub": "Bỏ qua kiểm tra trùng email",
    "import.fileLabel": "Chọn file (.xlsx)",
    "import.dropzone": "Kéo thả hoặc nhấn để chọn",
    "import.dropzoneSub": "Hỗ trợ file .xlsx",
    "import.fileReady": "File đã sẵn sàng · Nhấn để đổi",
    "import.processing": "Đang xử lý...",
    "import.cancel": "Huỷ",
    "import.start": "Bắt đầu tải lên",
    // Column labels
    "customers.col.selection": "Chọn",
    "customers.col.code": "Mã",
    "customers.col.fullName": "Họ và tên",
    "customers.col.location": "Cơ sở",
    "customers.col.school": "Trường học",
    "customers.col.type": "Phân loại",
    "customers.col.phone": "SĐT",
    "customers.col.dob": "Ngày sinh",
    "customers.col.email": "Email",
    "customers.col.parent1": "PH 1",
    "customers.col.phone1": "SĐT PH 1",
    "customers.col.parent2": "PH 2",
    "customers.col.phone2": "SĐT PH 2",
    "customers.col.parent3": "PH 3",
    "customers.col.phone3": "SĐT PH 3",
    "customers.col.parentAccounts": "Mã Phụ huynh",
    "customers.col.pipeline": "Mối quan hệ",
    "customers.col.source": "Nguồn",
    "customers.col.reject": "Lý do từ chối",
    "customers.col.sale": "Sale",
    "customers.col.manager": "Quản lý",
    "customers.col.teacher": "Giáo viên",
    "customers.col.classes": "Lớp học",
    "customers.col.accountStatus": "Trạng thái tài khoản",
    "customers.col.learningStatus": "Trạng thái học viên",
    "customers.col.address": "Địa chỉ",
    "customers.col.social": "Zalo/FB",
    "customers.col.zaloOA": "Zalo OA",
    "customers.col.level": "Trình độ",
    "customers.col.note": "Ghi chú",
    "customers.col.createdAt": "Ngày tạo",
    "customers.col.creator": "Người tạo",
    "customers.col.updatedAt": "Ngày cập nhật",
    "customers.col.updater": "Người cập nhật",
    "customers.col.appointmentNearest": "Lịch hẹn gần nhất",
    "customers.col.appointment1": "Lịch hẹn 1",
    "customers.col.appointment2": "Lịch hẹn 2",
    "customers.col.lastContact": "Lần cuối tiếp cận",
    "customers.col.discussion": "Thảo luận",
    "customers.col.actions": "Thao tác",
    // CustomerForm dialog
    "customerForm.sec1.title": "Thông tin cơ bản",
    "customerForm.sec1.subtitle": "Họ tên, mã, tài khoản, liên lạc",
    "customerForm.sec2.title": "Liên hệ",
    "customerForm.sec2.subtitle": "Thông tin phụ huynh, người giám hộ",
    "customerForm.sec3.title": "Phân loại & Chăm sóc",
    "customerForm.sec3.subtitle": "Nguồn, lớp học, sale, giáo viên, ghi chú",
    "customerForm.sec4.title": "Thông tin bổ sung",
    "customerForm.sec4.subtitle": "Các trường tùy chỉnh",
    "customerForm.avatar": "Ảnh đại diện",
    "customerForm.avatarUpload": "Tải ảnh",
    "customerForm.branch": "Cơ sở",
    "customerForm.selectBranch": "Chọn cơ sở",
    "customerForm.type": "Phân loại",
    "customerForm.selectType": "Chọn phân loại",
    "customerForm.typeStudent": "Học viên",
    "customerForm.typeParent": "Phụ huynh",
    "customerForm.code": "Mã",
    "customerForm.fullName": "Họ và tên",
    "customerForm.fullNamePlaceholder": "Nguyễn Văn A",
    "customerForm.account": "Tài khoản",
    "customerForm.password": "Mật khẩu",
    "customerForm.dob": "Sinh nhật",
    "customerForm.phone": "Số điện thoại",
    "customerForm.relationship": "Mối quan hệ",
    "customerForm.selectRelationship": "Chọn mối quan hệ",
    "customerForm.relationshipRequired": "Bắt buộc phải chọn mối quan hệ",
    "customerForm.parentLabel": "Phụ huynh",
    "customerForm.parentFullName": "Họ tên",
    "customerForm.parentPhone": "Số điện thoại",
    "customerForm.parentNamePlaceholder": "Tên phụ huynh",
    "customerForm.parentIds": "Mã Phụ huynh (tài khoản hệ thống)",
    "customerForm.selectParents": "Chọn phụ huynh đã có tài khoản...",
    "customerForm.parentIdsHint": "Gán học viên này với tài khoản phụ huynh đã được tạo trên hệ thống.",
    "customerForm.source": "Nguồn khách hàng",
    "customerForm.selectSource": "Chọn nguồn",
    "customerForm.rejectReason": "Lý do từ chối",
    "customerForm.noReason": "Chưa có lý do",
    "customerForm.none": "-- Không có --",
    "customerForm.class": "Lớp học",
    "customerForm.selectClass": "Chọn lớp học",
    "customerForm.accountStatus": "Trạng thái tài khoản",
    "customerForm.active": "Hoạt động",
    "customerForm.inactive": "Không hoạt động",
    "customerForm.sales": "Nhân viên Sale",
    "customerForm.selectSales": "Chọn nhân viên sale",
    "customerForm.manager": "Quản lý",
    "customerForm.selectManager": "Chọn quản lý",
    "customerForm.teacher": "Giáo viên",
    "customerForm.selectTeacher": "Chọn giáo viên",
    "customerForm.level": "Trình độ",
    "customerForm.levelPlaceholder": "VD: IELTS 5.0",
    "customerForm.address": "Địa chỉ",
    "customerForm.addressPlaceholder": "Địa chỉ...",
    "customerForm.social": "Zalo/FB",
    "customerForm.socialPlaceholder": "Link hoặc ID Zalo/Facebook...",
    "customerForm.note": "Ghi chú",
    "customerForm.notePlaceholder": "Nhập ghi chú thêm về học viên...",
    "customerForm.select": "Chọn",
    "customerForm.cancel": "Huỷ bỏ",
    "customerForm.checking": "Đang kiểm tra...",
    "customerForm.saving": "Đang lưu...",
    "customerForm.update": "Lưu",
    "customerForm.create": "Lưu",
    "customerForm.dupTitle": "Phát hiện thông tin trùng lặp",
    "customerForm.dupPhone": "Số điện thoại đã được dùng bởi:",
    "customerForm.dupPhoneLabel": "SĐT",
    "customerForm.dupEmail": "Email đã được dùng bởi:",
    "customerForm.dupConfirm": "Bạn có muốn tiếp tục lưu không?",
    "customerForm.dupCancel": "Huỷ",
    "customerForm.dupSave": "Cho phép trùng & Lưu",
    "customerForm.toastImageOnly": "Chỉ chấp nhận file ảnh",
    "customerForm.toastUploadFail": "Tải ảnh lên thất bại",
    "customerForm.toastRequiredTitle": "Vui lòng điền đầy đủ thông tin bắt buộc",
    "customerForm.toastRequiredDesc": "Kiểm tra lại các trường đánh dấu *",
    "customerForm.errCodeDupTitle": "Mã học viên đã tồn tại",
    "customerForm.errUsernameDupTitle": "Tài khoản đã tồn tại",
    // StudentDetailDialog tabs
    "studentDetail.tab.overview": "Tổng quan",
    "studentDetail.tab.appointments": "Lịch hẹn",
    "studentDetail.tab.discussion": "Thảo luận",
    "studentDetail.tab.classes": "Lớp học",
    "studentDetail.tab.feePackages": "Gói học phí",
    "studentDetail.tab.invoices": "Hoá đơn",
    "studentDetail.tab.feeWallet": "Ví học phí",
    "studentDetail.tab.scoreReview": "Bảng điểm - Nhận xét",
    "studentDetail.tab.score": "Bảng điểm",
    "studentDetail.tab.review": "Nhận xét",
    // StudentDetailDialog sidebar
    "studentDetail.sidebar.basicInfo": "Thông tin cơ bản",
    "studentDetail.sidebar.studentCode": "Mã học viên",
    "studentDetail.sidebar.type": "Loại",
    "studentDetail.sidebar.status": "Trạng thái",
    "studentDetail.sidebar.contact": "Liên hệ",
    "studentDetail.sidebar.phone": "Điện thoại",
    "studentDetail.sidebar.parents": "Phụ huynh",
    "studentDetail.sidebar.parent1": "Phụ huynh 1",
    "studentDetail.sidebar.parent2": "Phụ huynh 2",
    "studentDetail.sidebar.parent3": "Phụ huynh 3",
    "studentDetail.sidebar.otherInfo": "Thông tin khác",
    "studentDetail.sidebar.dob": "Ngày sinh",
    "studentDetail.sidebar.level": "Trình độ",
    "studentDetail.sidebar.source": "Nguồn KH",
    // StudentDetailDialog discussion
    "studentDetail.discussion.loading": "Đang tải...",
    "studentDetail.discussion.empty": "Chưa có thảo luận nào",
    "studentDetail.discussion.placeholder": "Nhập bình luận...",
    "studentDetail.discussion.send": "Gửi",
    // StudentDetailDialog classes
    "studentDetail.classes.loading": "Đang tải...",
    "studentDetail.classes.empty": "Học viên chưa đăng ký lớp nào",
    "studentDetail.classes.paid": "Đã thanh toán",
    "studentDetail.classes.attended": "Đã học",
    "studentDetail.classes.remaining": "Còn lại",
    "studentDetail.classes.notCheckedIn": "Chưa điểm danh",
    "studentDetail.classes.sessionCol": "Buổi học",
    "studentDetail.classes.shiftCol": "Ca học",
    "studentDetail.classes.dateCol": "Ngày",
    "studentDetail.classes.attendanceCol": "Điểm danh",
    "studentDetail.classes.feeNameCol": "Tên Học phí",
    "studentDetail.classes.baseFeeCol": "Học phí gốc",
    "studentDetail.classes.appliedFeeCol": "Học phí áp dụng",
    "studentDetail.classes.typeCol": "Loại",
    "studentDetail.classes.feeCol": "Học phí",
    "studentDetail.classes.sessionPrefix": "Buổi",
    "studentDetail.classes.shiftPrefix": "ca",
    "studentDetail.classes.present": "Có mặt",
    "studentDetail.classes.absent": "Vắng",
    "studentDetail.classes.noAttendance": "Chưa điểm danh",
    "studentDetail.classes.noSessions": "Không có buổi học nào",
    "studentDetail.classes.sessionsUnit": "buổi",
    "studentDetail.classes.show": "Hiển thị:",
    "studentDetail.classes.typeSession": "Buổi",
    "studentDetail.classes.typeCourse": "Khoá",
    // StudentDetailPage
    "studentDetail.notFound": "Không tìm thấy học viên.",
    "studentDetail.backToList": "Quay lại danh sách",
    // StudentOverviewTab
    "studentOverview.classes": "Lớp học",
    "studentOverview.enrolled": "Đang tham gia",
    "studentOverview.totalFees": "Tổng học phí",
    "studentOverview.paid": "Đã thanh toán",
    "studentOverview.debt": "Công nợ",
    "studentOverview.receivable": "Còn phải thu",
    "studentOverview.appointments": "Lịch hẹn",
    "studentOverview.today": "Hôm nay",
    "studentOverview.yesterday": "Hôm qua",
    "studentOverview.noAppointments": "Không có lịch hẹn",
    "studentOverview.taskDone": "Hoàn tất",
    "studentOverview.taskOverdue": "Quá hạn",
    "studentOverview.taskDue": "Hạn cuối:",
    "studentOverview.taskStaff": "Nhân sự:",
    "studentOverview.moreTasks": "công việc khác",
    "studentOverview.viewAll": "Xem tất cả",
    "studentOverview.saving": "Đang lưu…",
    "studentOverview.saved": "Đã lưu",
    "studentOverview.notePlaceholder": "Nhập thông tin quan trọng về học viên — tính cách, nhu cầu, lưu ý đặc biệt…",
    "studentOverview.additionalInfo": "Thông tin bổ sung",
    "studentOverview.gender": "Giới tính",
    "studentOverview.address": "Địa chỉ",
    "studentOverview.school": "Trường học",
    "studentOverview.source": "Nguồn KH",
    "studentOverview.socialMedia": "Mạng xã hội",
    "studentOverview.sales": "Sale",
    "studentOverview.manager": "Quản lý",
    "studentOverview.parent": "Phụ huynh",
    "studentOverview.parent2": "Phụ huynh 2",
    "studentOverview.parent3": "Phụ huynh 3",
    "studentOverview.relationship": "Quan hệ",
    "studentOverview.createdDate": "Ngày tạo",
    "studentOverview.classInfo": "Thông tin lớp học",
    "studentOverview.classesUnit": "lớp",
    "studentOverview.noClasses": "Chưa tham gia lớp nào",
    "studentOverview.statusActive": "Đang học",
    "studentOverview.statusDropped": "Bỏ học",
    "studentOverview.statusCompleted": "Hoàn thành",
    "studentOverview.statusPaused": "Tạm dừng",
    "studentOverview.paymentHistory": "Lịch sử thanh toán",
    "studentOverview.tuition": "Học phí",
    "studentOverview.noPayments": "Chưa có dữ liệu thanh toán",
    "studentOverview.paidStatus": "Đã TT",
    "studentOverview.stars": "Sao khả dụng:",
    "studentOverview.eventNote": "Ghi chú",
    "studentOverview.eventPresent": "Điểm danh",
    "studentOverview.eventAbsent": "Vắng mặt",
    "studentOverview.eventPayment": "Thanh toán",
    "studentOverview.classPrefix": "Lớp học",
    "studentOverview.sessionPrefix": "Buổi học",
    "studentOverview.shiftPrefix": "ca",

    // ── Calendar page ─────────────────────────────────────────────
    "calendar.title": "Lịch cá nhân",
    "calendar.today": "Hôm nay",
    "calendar.noSchedule": "KHÔNG CÓ LỊCH",
    "calendar.sessionCount": "CA HỌC",
    "calendar.errorLoad": "Không thể tải lịch. Vui lòng thử lại.",
    "calendar.viewList": "Danh sách",
    "calendar.viewCalendar": "Lịch",
    "calendar.page.notInDaoTao": "Tài khoản không thuộc Phòng Đào tạo nên không có quyền xem trang này",
    "calendar.page.notLinked": "Tài khoản chưa được liên kết với học viên hoặc nhân viên",
    "calendar.staff.noSessions": "Không có buổi dạy nào trong ngày này",
    "calendar.student.noSessions": "Không có buổi học nào trong ngày này",
    "calendar.student.noCourses": "Chưa có buổi học nào được ghi nhận",
    "calendar.student.errorLoadSessions": "Không thể tải buổi học. Vui lòng thử lại.",
    "calendar.student.errorLoadClasses": "Không thể tải danh sách. Vui lòng thử lại.",
    "calendar.student.table.session": "Buổi học",
    "calendar.student.table.slot": "Ca học",
    "calendar.student.table.date": "Ngày",
    "calendar.student.table.attendance": "Điểm danh",
    "calendar.student.table.feedback": "Nhận xét",
    "calendar.student.table.noSessions": "Chưa có buổi học nào",
    "calendar.student.table.show": "Hiển thị",
    "calendar.student.table.perPage": "/ trang",
    "calendar.student.table.sessionUnit": "buổi",
    "calendar.student.table.viewFeedback": "Xem nhận xét",
    "calendar.attendance.pending": "Chưa điểm danh",
    "calendar.attendance.present": "Có học",
    "calendar.attendance.absent": "Nghỉ học",
    "calendar.attendance.makeup_wait": "Nghỉ chờ bù",
    "calendar.attendance.makeup_done": "Đã học bù",
    "calendar.attendance.paused": "Bảo lưu",
    "calendar.card.time": "Thời gian:",
    "calendar.card.class": "Lớp:",
    "calendar.card.teacher": "GV:",
    "calendar.card.student": "HV:",
    "calendar.card.ended": "Đã kết thúc",
    "calendar.card.loading": "Đang tải nội dung...",
    "calendar.card.generalContent": "Nội dung chung",
    "calendar.card.personalContent": "Nội dung cá nhân",
    "calendar.card.feedbackLabel": "Nhận xét:",
    "calendar.card.viewFeedback": "Xem nhận xét",
    "calendar.card.noFeedback": "Chưa có nhận xét",
    "calendar.card.endOnline": "Kết thúc học online",
    "calendar.card.buttonOpensAt": "Nút sẽ mở lúc",
    "calendar.card.joinedAt": "Đã vào lúc",
    "calendar.card.endedAt": "Kết thúc lúc",
    "calendar.card.testNotOpen": "Bài test chưa mở",
    "calendar.card.testStartsAt": "Sẽ được bắt đầu lúc",
    "calendar.card.close": "Đóng",
    "calendar.card.cantOpen": "Không thể mở bài",
    "calendar.card.testEnded": "Lịch test đã kết thúc",
    "calendar.card.testEndedAt": "đã kết thúc lúc",
    "calendar.card.testEndedOn": "ngày",
    "calendar.card.contentUnavailable": "Nội dung không còn khả dụng.",
    "calendar.staff.card.size": "Sĩ số:",
    "calendar.staff.card.teachers": "Giáo viên:",
    "calendar.staff.card.cancelled": "Đã huỷ",
    "calendar.staff.card.addTest": "Thêm bài test",
    "calendar.staff.card.addContent": "Thêm nội dung",
    "calendar.staff.card.assignContent": "Giao nội dung",
    "calendar.staff.card.loading": "Đang tải...",
    "calendar.staff.card.errorLoad": "Không thể tải chi tiết buổi dạy",
    "calendar.staff.card.generalContent": "Nội dung chung",
    "calendar.staff.card.notMarked": "Chưa điểm danh",
    "calendar.staff.card.marked": "Đã điểm danh",
    "calendar.staff.card.noReview": "Chưa nhận xét",
    "calendar.staff.card.reviewed": "Đã nhận xét",
    "calendar.staff.card.exam": "Bài kiểm tra",
    "calendar.staff.card.homework": "BTVN",
    "calendar.detail.time": "Thời gian:",
    "calendar.detail.location": "Cơ sở:",
    "calendar.detail.sessionNum": "Buổi học:",
    "calendar.detail.room": "Phòng học:",
    "calendar.detail.teacher": "Giáo viên:",
    "calendar.detail.studentCount": "Học viên:",
    "calendar.detail.format": "Hình thức:",
    "calendar.detail.empty": "Trống",
    "calendar.detail.studentList": "Danh sách học viên buổi",
    "calendar.detail.actions": "Hành động",
    "calendar.detail.bulkAttendance": "Điểm danh hàng loạt",
    "calendar.detail.bulkReview": "Nhận xét hàng loạt",
    "calendar.detail.removeStudent": "Xóa học viên",
    "calendar.detail.assignContent": "Giao nội dung",
    "calendar.detail.colName": "Tên học viên",
    "calendar.detail.colAttendance": "Điểm danh",
    "calendar.detail.colNote": "Ghi chú",
    "calendar.detail.colReview": "Nhận xét",
    "calendar.detail.noStudents": "Chưa có học viên trong buổi học này",
    "calendar.detail.bulkTitle": "Điểm danh hàng loạt",
    "calendar.detail.bulkDesc": "Chọn trạng thái điểm danh cho",
    "calendar.detail.bulkDescSuffix": "học viên được chọn",
    "calendar.detail.reviewedBtn": "Đã nhận xét",
    "calendar.detail.addReview": "Thêm",
    "calendar.detail.notePlaceholder": "Ghi chú...",
    "calendar.detail.noDescription": "Không có mô tả",
    "calendar.feedback.title": "Nhận xét từ Giáo viên",
    "calendar.feedback.class": "Lớp",
    "calendar.feedback.criteria": "Đánh giá theo tiêu chí",
    "calendar.feedback.loading": "Đang tải nhận xét...",
    "calendar.feedback.empty": "Chưa có nhận xét",
    "calendar.feedback.noComment": "Chưa có nhận xét",
    "calendar.feedback.thanks": "💙 Cảm ơn thầy/cô đã nhận xét!",
  },
  en: {
    "login.welcome": "Welcome back",
    "login.subtitle": "Sign in to EduManage education management system",
    "login.username": "Username",
    "login.password": "Password",
    "login.forgot": "Forgot password?",
    "login.submit": "Sign In",
    "login.loading": "Signing in...",
    "login.footer": "Education Management System",
    "login.cover.title": "Optimize Your Operations",
    "login.cover.desc": "A comprehensive solution for managing education centers, tracking students, classes and finances in one unified, efficient and smart platform.",
    "notification.title": "Notifications",
    "notification.markAll": "Mark all read",
    "notification.loading": "Loading...",
    "notification.empty": "No notifications",
    "notification.viewDetail": "View detail →",
    "notification.collapse": "Collapse",
    "notification.expand": "Show more",
    "sidebar.logout": "Sign Out",
    "sidebar.system": "System",
    "sidebar.location": "Branch:",
    "sidebar.allLocations": "All branches",
    // Customers page
    "customers.statTotal": "Total",
    "customers.statActive": "Active",
    "customers.statNoSchedule": "No Schedule",
    "customers.statDeferred": "Deferred",
    "customers.statInactive": "Inactive",
    "customers.addStudent": "Add Student",
    "customers.searchPlaceholder": "Search by Name, Code...",
    "customers.upload": "Upload",
    "customers.download": "Download",
    "customers.columns": "Columns",
    "customers.columnSettings": "Column Settings",
    "customers.columnDragHint": "Drag to reorder",
    "customers.searchColumns": "Search columns...",
    "customers.actions": "Actions",
    "customers.actionsCount": "Actions ({{n}})",
    "customers.bulkActions": "Bulk Actions",
    "customers.bulkRelationship": "Relationship",
    "customers.bulkBranch": "Assign Branch",
    "customers.bulkSale": "Assign Sale",
    "customers.bulkManager": "Assign Manager",
    "customers.bulkTeacher": "Assign Teacher",
    "customers.bulkParent": "Assign Parent",
    "customers.bulkClass": "Assign Class",
    "customers.bulkAccountStatus": "Account Status",
    "customers.bulkDelete": "Delete {{n}} students",
    "customers.selectToAction": "Select students to perform actions",
    "customers.filter": "Filters",
    "customers.filterAdvanced": "Advanced Filters",
    "customers.filterApplied": "Filters applied",
    "customers.filterClearAll": "Clear all",
    "customers.filterBranch": "Branch",
    "customers.filterType": "Type",
    "customers.filterSource": "Source",
    "customers.filterRejectReason": "Rejection Reason",
    "customers.filterSale": "Sale",
    "customers.filterManager": "Manager",
    "customers.filterTeacher": "Teacher",
    "customers.filterClass": "Class",
    "customers.filterSchool": "School",
    "customers.filterBirthYear": "Birth year",
    "customers.filterCreatedFrom": "Created From",
    "customers.filterTo": "To",
    "customers.filterUpdatedFrom": "Updated From",
    "customers.filterAccountStatus": "Account Status",
    "customers.filterStudentStatus": "Student Status",
    "customers.filterBirthdayFrom": "Birthday From",
    "customers.allBranches": "All Branches",
    "customers.allTypes": "All Types",
    "customers.typeStudent": "Student",
    "customers.typeParent": "Parent",
    "customers.selectSource": "Select source",
    "customers.selectReason": "Select reason",
    "customers.selectSale": "Select sale",
    "customers.selectManager": "Select manager",
    "customers.selectTeacher": "Select teacher",
    "customers.selectClass": "Select class",
    "customers.selectSchool": "Select school",
    "customers.selectBirthYear": "Select birth year",
    "customers.selectStatus": "Select status",
    "customers.selectDay": "Day",
    "customers.selectMonth": "Month",
    "customers.statusActive": "Active",
    "customers.statusInactive": "Inactive",
    "customers.statusLearning": "Studying",
    "customers.statusWaiting": "Waiting",
    "customers.statusDeferred": "Deferred",
    "customers.statusDropped": "Dropped",
    "customers.statusNoSchedule": "No Schedule",
    "customers.filterAll": "All",
    "customers.showing": "Showing",
    "customers.of": "/",
    "customers.results": "results",
    "customers.rowsPerPage": "Rows:",
    "customers.addDialogTitle": "Add New Student",
    "customers.addDialogDesc": "Fill in all information below to create a new student profile.",
    "customers.editDialogTitle": "Edit Student",
    "customers.editDialogDesc": "Update student profile information.",
    "customers.activityLog": "Activity Log",
    "customers.confirmDelete": "Are you sure you want to delete this student?",
    "customers.toastCreated": "New student added.",
    "customers.toastUpdated": "Student information updated.",
    "customers.toastUpdateError": "Unable to update student information.",
    "customers.toastDeleted": "Student deleted.",
    "customers.toastDeleteError": "Unable to delete student.",
    "customers.toastRelUpdated": "Relationship updated.",
    "customers.toastRelError": "Unable to update relationship.",
    "customers.toastStatusUpdated": "Account status updated.",
    "customers.toastStatusError": "Unable to update status.",
    "common.success": "Success",
    "common.error": "Error",
    "header.search": "Search...",
    "header.selectBranch": "Select branch",
    // Import dialog
    "import.title": "Import Student List",
    "import.titleResult": "Import Results",
    "import.subtitle": "Upload an .xlsx file to import quickly.",
    "import.subtitleResult": "The system has finished processing your Excel file.",
    "import.successCount": "Successfully imported",
    "import.errorCount": "Error rows",
    "import.errorDetail": "Error row details",
    "import.rows": "rows",
    "import.row": "Row",
    "import.errorInfo": "Download the error file to see highlighted cells with reasons, fix them and re-import.",
    "import.downloadErrors": "Download error file ({{n}} rows)",
    "import.importAgain": "Import Again",
    "import.close": "Close",
    "import.template": "Download Excel Template",
    "import.templateSub": "View standard format before importing",
    "import.notice": "File format notes:",
    "import.noticeCol": "Columns B, D, N are required",
    "import.noticeCode": "Empty code → Auto-generated (HV-01...)",
    "import.noticeDropdown": "Use available dropdowns in the Excel file",
    "import.location": "Branch",
    "import.locationOptional": "(optional)",
    "import.locationPlaceholder": "Select branch",
    "import.allowDupePhone": "Allow duplicate phone",
    "import.allowDupePhoneSub": "Skip duplicate phone number check",
    "import.allowDupeEmail": "Allow duplicate email",
    "import.allowDupeEmailSub": "Skip duplicate email check",
    "import.fileLabel": "Select file (.xlsx)",
    "import.dropzone": "Drag & drop or click to select",
    "import.dropzoneSub": "Supports .xlsx files",
    "import.fileReady": "File ready · Click to change",
    "import.processing": "Processing...",
    "import.cancel": "Cancel",
    "import.start": "Start Upload",
    // Column labels
    "customers.col.selection": "Select",
    "customers.col.code": "Code",
    "customers.col.fullName": "Full Name",
    "customers.col.location": "Branch",
    "customers.col.school": "School",
    "customers.col.type": "Type",
    "customers.col.phone": "Phone",
    "customers.col.dob": "Date of Birth",
    "customers.col.email": "Email",
    "customers.col.parent1": "Parent 1",
    "customers.col.phone1": "Parent 1 Phone",
    "customers.col.parent2": "Parent 2",
    "customers.col.phone2": "Parent 2 Phone",
    "customers.col.parent3": "Parent 3",
    "customers.col.phone3": "Parent 3 Phone",
    "customers.col.parentAccounts": "Parent Codes",
    "customers.col.pipeline": "Relationship",
    "customers.col.source": "Source",
    "customers.col.reject": "Rejection Reason",
    "customers.col.sale": "Sale",
    "customers.col.manager": "Manager",
    "customers.col.teacher": "Teacher",
    "customers.col.classes": "Classes",
    "customers.col.accountStatus": "Account Status",
    "customers.col.learningStatus": "Student Status",
    "customers.col.address": "Address",
    "customers.col.social": "Zalo/FB",
    "customers.col.zaloOA": "Zalo OA",
    "customers.col.level": "Level",
    "customers.col.note": "Note",
    "customers.col.createdAt": "Created Date",
    "customers.col.creator": "Created By",
    "customers.col.updatedAt": "Updated Date",
    "customers.col.updater": "Updated By",
    "customers.col.appointmentNearest": "Nearest Appointment",
    "customers.col.appointment1": "Appointment 1",
    "customers.col.appointment2": "Appointment 2",
    "customers.col.lastContact": "Last Contact",
    "customers.col.discussion": "Discussion",
    "customers.col.actions": "Actions",
    // CustomerForm dialog
    "customerForm.sec1.title": "Basic Information",
    "customerForm.sec1.subtitle": "Name, code, account, contact",
    "customerForm.sec2.title": "Contact",
    "customerForm.sec2.subtitle": "Parent and guardian information",
    "customerForm.sec3.title": "Classification & Care",
    "customerForm.sec3.subtitle": "Source, class, sale, teacher, notes",
    "customerForm.sec4.title": "Additional Information",
    "customerForm.sec4.subtitle": "Custom fields",
    "customerForm.avatar": "Avatar",
    "customerForm.avatarUpload": "Upload",
    "customerForm.branch": "Branch",
    "customerForm.selectBranch": "Select branch",
    "customerForm.type": "Type",
    "customerForm.selectType": "Select type",
    "customerForm.typeStudent": "Student",
    "customerForm.typeParent": "Parent",
    "customerForm.code": "Code",
    "customerForm.fullName": "Full Name",
    "customerForm.fullNamePlaceholder": "John Smith",
    "customerForm.account": "Account",
    "customerForm.password": "Password",
    "customerForm.dob": "Date of Birth",
    "customerForm.phone": "Phone Number",
    "customerForm.relationship": "Relationship",
    "customerForm.selectRelationship": "Select relationship",
    "customerForm.relationshipRequired": "Relationship is required",
    "customerForm.parentLabel": "Parent",
    "customerForm.parentFullName": "Full Name",
    "customerForm.parentPhone": "Phone Number",
    "customerForm.parentNamePlaceholder": "Parent name",
    "customerForm.parentIds": "Parent Code (system account)",
    "customerForm.selectParents": "Select parents with existing accounts...",
    "customerForm.parentIdsHint": "Assign this student to a parent account already created in the system.",
    "customerForm.source": "Customer Source",
    "customerForm.selectSource": "Select source",
    "customerForm.rejectReason": "Rejection Reason",
    "customerForm.noReason": "No reasons available",
    "customerForm.none": "-- None --",
    "customerForm.class": "Class",
    "customerForm.selectClass": "Select class",
    "customerForm.accountStatus": "Account Status",
    "customerForm.active": "Active",
    "customerForm.inactive": "Inactive",
    "customerForm.sales": "Sales Staff",
    "customerForm.selectSales": "Select sales staff",
    "customerForm.manager": "Manager",
    "customerForm.selectManager": "Select manager",
    "customerForm.teacher": "Teacher",
    "customerForm.selectTeacher": "Select teacher",
    "customerForm.level": "Level",
    "customerForm.levelPlaceholder": "E.g. IELTS 5.0",
    "customerForm.address": "Address",
    "customerForm.addressPlaceholder": "Address...",
    "customerForm.social": "Zalo/FB",
    "customerForm.socialPlaceholder": "Zalo/Facebook link or ID...",
    "customerForm.note": "Note",
    "customerForm.notePlaceholder": "Enter additional notes about the student...",
    "customerForm.select": "Select",
    "customerForm.cancel": "Cancel",
    "customerForm.checking": "Checking...",
    "customerForm.saving": "Saving...",
    "customerForm.update": "Save",
    "customerForm.create": "Save",
    "customerForm.dupTitle": "Duplicate Information Detected",
    "customerForm.dupPhone": "Phone number already used by:",
    "customerForm.dupPhoneLabel": "Phone",
    "customerForm.dupEmail": "Email already used by:",
    "customerForm.dupConfirm": "Do you want to continue saving?",
    "customerForm.dupCancel": "Cancel",
    "customerForm.dupSave": "Allow Duplicate & Save",
    "customerForm.toastImageOnly": "Only image files are accepted",
    "customerForm.toastUploadFail": "Failed to upload image",
    "customerForm.toastRequiredTitle": "Please fill in all required fields",
    "customerForm.toastRequiredDesc": "Check fields marked with *",
    "customerForm.errCodeDupTitle": "Student code already exists",
    "customerForm.errUsernameDupTitle": "Account already exists",
    // StudentDetailDialog tabs
    "studentDetail.tab.overview": "Overview",
    "studentDetail.tab.appointments": "Appointments",
    "studentDetail.tab.discussion": "Discussion",
    "studentDetail.tab.classes": "Classes",
    "studentDetail.tab.feePackages": "Fee Packages",
    "studentDetail.tab.invoices": "Invoices",
    "studentDetail.tab.feeWallet": "Fee Wallet",
    "studentDetail.tab.scoreReview": "Score Sheet - Reviews",
    "studentDetail.tab.score": "Score Sheet",
    "studentDetail.tab.review": "Reviews",
    // StudentDetailDialog sidebar
    "studentDetail.sidebar.basicInfo": "Basic Information",
    "studentDetail.sidebar.studentCode": "Student Code",
    "studentDetail.sidebar.type": "Type",
    "studentDetail.sidebar.status": "Status",
    "studentDetail.sidebar.contact": "Contact",
    "studentDetail.sidebar.phone": "Phone",
    "studentDetail.sidebar.parents": "Parents",
    "studentDetail.sidebar.parent1": "Parent 1",
    "studentDetail.sidebar.parent2": "Parent 2",
    "studentDetail.sidebar.parent3": "Parent 3",
    "studentDetail.sidebar.otherInfo": "Other Information",
    "studentDetail.sidebar.dob": "Date of Birth",
    "studentDetail.sidebar.level": "Level",
    "studentDetail.sidebar.source": "Customer Source",
    // StudentDetailDialog discussion
    "studentDetail.discussion.loading": "Loading...",
    "studentDetail.discussion.empty": "No discussions yet",
    "studentDetail.discussion.placeholder": "Enter a comment...",
    "studentDetail.discussion.send": "Send",
    // StudentDetailDialog classes
    "studentDetail.classes.loading": "Loading...",
    "studentDetail.classes.empty": "Student is not enrolled in any classes",
    "studentDetail.classes.paid": "Paid",
    "studentDetail.classes.attended": "Attended",
    "studentDetail.classes.remaining": "Remaining",
    "studentDetail.classes.notCheckedIn": "Not Checked In",
    "studentDetail.classes.sessionCol": "Session",
    "studentDetail.classes.shiftCol": "Shift",
    "studentDetail.classes.dateCol": "Date",
    "studentDetail.classes.attendanceCol": "Attendance",
    "studentDetail.classes.feeNameCol": "Fee Package",
    "studentDetail.classes.baseFeeCol": "Base Fee",
    "studentDetail.classes.appliedFeeCol": "Applied Fee",
    "studentDetail.classes.typeCol": "Type",
    "studentDetail.classes.feeCol": "Fee",
    "studentDetail.classes.sessionPrefix": "Session",
    "studentDetail.classes.shiftPrefix": "shift",
    "studentDetail.classes.present": "Present",
    "studentDetail.classes.absent": "Absent",
    "studentDetail.classes.noAttendance": "Not checked in",
    "studentDetail.classes.noSessions": "No sessions found",
    "studentDetail.classes.sessionsUnit": "sessions",
    "studentDetail.classes.show": "Show:",
    "studentDetail.classes.typeSession": "Session",
    "studentDetail.classes.typeCourse": "Course",
    // StudentDetailPage
    "studentDetail.notFound": "Student not found.",
    "studentDetail.backToList": "Back to list",
    // StudentOverviewTab
    "studentOverview.classes": "Classes",
    "studentOverview.enrolled": "Enrolled",
    "studentOverview.totalFees": "Total Fees",
    "studentOverview.paid": "Paid",
    "studentOverview.debt": "Debt",
    "studentOverview.receivable": "Receivable",
    "studentOverview.appointments": "Appointments",
    "studentOverview.today": "Today",
    "studentOverview.yesterday": "Yesterday",
    "studentOverview.noAppointments": "No appointments",
    "studentOverview.taskDone": "Done",
    "studentOverview.taskOverdue": "Overdue",
    "studentOverview.taskDue": "Due:",
    "studentOverview.taskStaff": "Staff:",
    "studentOverview.moreTasks": "more tasks",
    "studentOverview.viewAll": "View all",
    "studentOverview.saving": "Saving…",
    "studentOverview.saved": "Saved",
    "studentOverview.notePlaceholder": "Enter important information about the student — personality, needs, special notes…",
    "studentOverview.additionalInfo": "Additional Information",
    "studentOverview.gender": "Gender",
    "studentOverview.address": "Address",
    "studentOverview.school": "School",
    "studentOverview.source": "Customer Source",
    "studentOverview.socialMedia": "Social Media",
    "studentOverview.sales": "Sales",
    "studentOverview.manager": "Manager",
    "studentOverview.parent": "Parent",
    "studentOverview.parent2": "Parent 2",
    "studentOverview.parent3": "Parent 3",
    "studentOverview.relationship": "Relationship",
    "studentOverview.createdDate": "Created Date",
    "studentOverview.classInfo": "Class Information",
    "studentOverview.classesUnit": "classes",
    "studentOverview.noClasses": "No classes enrolled",
    "studentOverview.statusActive": "Active",
    "studentOverview.statusDropped": "Dropped",
    "studentOverview.statusCompleted": "Completed",
    "studentOverview.statusPaused": "Paused",
    "studentOverview.paymentHistory": "Payment History",
    "studentOverview.tuition": "Tuition",
    "studentOverview.noPayments": "No payment data",
    "studentOverview.paidStatus": "Paid",
    "studentOverview.stars": "Available stars:",
    "studentOverview.eventNote": "Note",
    "studentOverview.eventPresent": "Attendance",
    "studentOverview.eventAbsent": "Absent",
    "studentOverview.eventPayment": "Payment",
    "studentOverview.classPrefix": "Class",
    "studentOverview.sessionPrefix": "Session",
    "studentOverview.shiftPrefix": "shift",
  },
};

const navMap: Record<string, string> = {
  // ── Top-level items ──────────────────────────────────────────
  "Dashboard": "Dashboard",
  "Bảng tin": "News Feed",
  "Chat": "Chat",
  "Zalo OA": "Zalo OA",

  // ── Module names ─────────────────────────────────────────────
  "MY SPACE": "MY SPACE",
  "CÔNG VIỆC": "TASKS",
  "CRM": "CRM",
  "HRM": "HRM",
  "EDUCATION": "EDUCATION",
  "FINANCE": "FINANCE",
  "STORE (KHO)": "STORE",
  "SETTING": "SETTINGS",

  // ── MY SPACE items ───────────────────────────────────────────
  "Lịch cá nhân": "My Calendar",
  "Bài tập của tôi": "My Assignments",
  "Bảng điểm của tôi": "My Score Sheet",
  "Hoá đơn của tôi": "My Invoices",
  "Bảng lương của tôi": "My Payroll",

  // ── CÔNG VIỆC items ──────────────────────────────────────────
  "Công việc": "Tasks",
  "Danh sách công việc": "Task List",
  "Cấu hình công việc": "Task Settings",

  // ── CRM items ────────────────────────────────────────────────
  "Khách hàng": "Customers",
  "Cấu hình CRM": "CRM Settings",
  "Lịch sử thông báo": "Notification History",
  "Mối quan hệ": "Relationships",
  "Lý do từ chối": "Rejection Reasons",
  "Nguồn khách hàng": "Customer Sources",
  "Thông tin bổ sung": "Additional Info",
  "Thông tin bắt buộc": "Required Info",

  // ── HRM items ────────────────────────────────────────────────
  "Nhân sự": "Staff",
  "Đơn từ": "Leave Requests",
  "Ca làm việc": "Work Shifts",
  "Bảng chấm công": "Attendance Sheet",
  "Lương đứng lớp": "Teaching Salary",
  "Tổng lương": "Total Salary",
  "Đăng ký ca dạy": "Teaching Shift Register",
  "Bảng phân ca": "Shift Board",
  "Phân ca làm việc": "Shift Assignment",
  "Cấu hình ca làm việc": "Shift Settings",
  "Bảng lương đứng lớp": "Teaching Salary Table",
  "Gói lương đứng lớp": "Teaching Salary Packages",
  "Cấu hình theo nhân sự": "Staff Config",
  "Bảng tổng lương": "Total Salary Sheet",
  "Cấu hình Lương nhân sự": "Staff Salary Config",
  "Cấu hình mặc định": "Default Config",

  // ── EDUCATION items ──────────────────────────────────────────
  "Tổng quan học tập": "Learning Overview",
  "Lớp học": "Classes",
  "Lịch học": "Schedule",
  "Điểm danh": "Attendance",
  "Khoá học & Chương trình": "Courses & Programs",
  "Bài kiểm tra": "Assessments",
  "Cấu hình Education": "Education Settings",
  "Tổng quan học viên": "Student Overview",
  "Học viên sắp hết lịch": "Students Ending Soon",
  "Lớp học sắp kết thúc": "Classes Ending Soon",
  "Chờ bù - Bảo lưu": "Makeup - Deferred",
  "Bảng điểm": "Score Sheet",
  "Bài tập về nhà": "Homework",
  "Nhận xét học viên": "Student Reviews",
  "Chấm công giáo viên": "Teacher Attendance",
  "Khoá học": "Courses",
  "Chương trình học": "Programs",
  "Thư viện nội dung": "Content Library",
  "Danh sách Bài kiểm tra": "Assessment List",
  "Ngân hàng câu hỏi": "Question Bank",
  "Kết quả bài làm": "Exam Results",
  "Phòng học": "Classrooms",
  "Bộ môn": "Subjects",
  "Tiêu chí đánh giá": "Evaluation Criteria",
  "Ca học": "Class Sessions",
  "Trừ tiền học phí": "Tuition Deduction",
  "Bảng điểm mẫu": "Score Sheet Templates",
  "Học online": "Online Learning",

  // ── FINANCE items ────────────────────────────────────────────
  "Hoá đơn": "Invoices",
  "Cấu hình tài chính": "Finance Settings",
  "Khuyến mãi / Phụ thu": "Promotions / Surcharges",
  "Danh mục Thu Chi": "Income & Expenses",

  // ── STORE items ──────────────────────────────────────────────
  "Kho hàng": "Warehouse",
  "Nhập kho": "Stock Import",
  "Xuất kho": "Stock Export",
  "Chuyển kho": "Stock Transfer",
  "Tồn kho": "Inventory",
  "Sản phẩm": "Products",
  "Cấu hình kho": "Warehouse Settings",

  // ── SETTING items ────────────────────────────────────────────
  "Cấu hình hệ thống": "System Settings",
  "Cơ sở": "Branches",
  "Phòng ban & Vai trò": "Departments & Roles",
  "Quản lý hệ thống": "System Management",
  "Quản lý phân quyền": "Permissions",
  "Tài khoản AI": "AI Accounts",
  "Kết nối nhà cung cấp": "Provider Connections",
  "Ngày nghỉ lễ": "Public Holidays",
  "Cổng thanh toán": "Payment Gateway",
  "Hoá đơn điện tử": "E-Invoice",

  // ── Dashboard subTabs ────────────────────────────────────────
  "Đào tạo": "Training",
  "Tài chính": "Finance",
  "Báo cáo": "Reports",
};

const enCalendar: Record<string, string> = {
  // ── Calendar page ─────────────────────────────────────────────
  "calendar.title": "Personal Calendar",
  "calendar.today": "Today",
  "calendar.noSchedule": "NO SCHEDULE",
  "calendar.sessionCount": "SESSIONS",
  "calendar.errorLoad": "Unable to load calendar. Please try again.",
  "calendar.viewList": "List",
  "calendar.viewCalendar": "Calendar",
  "calendar.page.notInDaoTao": "This account does not belong to the Training Department and cannot view this page",
  "calendar.page.notLinked": "This account is not linked to a student or staff member",
  "calendar.staff.noSessions": "No teaching sessions on this day",
  "calendar.student.noSessions": "No classes on this day",
  "calendar.student.noCourses": "No sessions recorded yet",
  "calendar.student.errorLoadSessions": "Unable to load sessions. Please try again.",
  "calendar.student.errorLoadClasses": "Unable to load class list. Please try again.",
  "calendar.student.table.session": "Session",
  "calendar.student.table.slot": "Slot",
  "calendar.student.table.date": "Date",
  "calendar.student.table.attendance": "Attendance",
  "calendar.student.table.feedback": "Feedback",
  "calendar.student.table.noSessions": "No sessions yet",
  "calendar.student.table.show": "Show",
  "calendar.student.table.perPage": "/ page",
  "calendar.student.table.sessionUnit": "sessions",
  "calendar.student.table.viewFeedback": "View feedback",
  "calendar.attendance.pending": "Not marked",
  "calendar.attendance.present": "Present",
  "calendar.attendance.absent": "Absent",
  "calendar.attendance.makeup_wait": "Absent (makeup pending)",
  "calendar.attendance.makeup_done": "Makeup done",
  "calendar.attendance.paused": "Paused",
  "calendar.card.time": "Time:",
  "calendar.card.class": "Class:",
  "calendar.card.teacher": "Teacher:",
  "calendar.card.student": "Student:",
  "calendar.card.ended": "Ended",
  "calendar.card.loading": "Loading content...",
  "calendar.card.generalContent": "General content",
  "calendar.card.personalContent": "Personal content",
  "calendar.card.feedbackLabel": "Feedback:",
  "calendar.card.viewFeedback": "View feedback",
  "calendar.card.noFeedback": "No feedback yet",
  "calendar.card.endOnline": "End online session",
  "calendar.card.buttonOpensAt": "Button opens at",
  "calendar.card.joinedAt": "Joined at",
  "calendar.card.endedAt": "Ended at",
  "calendar.card.testNotOpen": "Test not yet available",
  "calendar.card.testStartsAt": "Will start at",
  "calendar.card.close": "Close",
  "calendar.card.cantOpen": "Cannot open",
  "calendar.card.testEnded": "Test session ended",
  "calendar.card.testEndedAt": "ended at",
  "calendar.card.testEndedOn": "on",
  "calendar.card.contentUnavailable": "Content is no longer available.",
  "calendar.staff.card.size": "Enrollment:",
  "calendar.staff.card.teachers": "Teacher(s):",
  "calendar.staff.card.cancelled": "Cancelled",
  "calendar.staff.card.addTest": "Add test",
  "calendar.staff.card.addContent": "Add content",
  "calendar.staff.card.assignContent": "Assign content",
  "calendar.staff.card.loading": "Loading...",
  "calendar.staff.card.errorLoad": "Unable to load session details",
  "calendar.staff.card.generalContent": "General content",
  "calendar.staff.card.notMarked": "Not marked",
  "calendar.staff.card.marked": "Marked",
  "calendar.staff.card.noReview": "No review",
  "calendar.staff.card.reviewed": "Reviewed",
  "calendar.staff.card.exam": "Assessment",
  "calendar.staff.card.homework": "Homework",
  "calendar.detail.time": "Time:",
  "calendar.detail.location": "Branch:",
  "calendar.detail.sessionNum": "Session:",
  "calendar.detail.room": "Room:",
  "calendar.detail.teacher": "Teacher(s):",
  "calendar.detail.studentCount": "Students:",
  "calendar.detail.format": "Format:",
  "calendar.detail.empty": "None",
  "calendar.detail.studentList": "Session student list",
  "calendar.detail.actions": "Actions",
  "calendar.detail.bulkAttendance": "Bulk attendance",
  "calendar.detail.bulkReview": "Bulk review",
  "calendar.detail.removeStudent": "Remove student",
  "calendar.detail.assignContent": "Assign content",
  "calendar.detail.colName": "Student name",
  "calendar.detail.colAttendance": "Attendance",
  "calendar.detail.colNote": "Note",
  "calendar.detail.colReview": "Feedback",
  "calendar.detail.noStudents": "No students in this session",
  "calendar.detail.bulkTitle": "Bulk attendance",
  "calendar.detail.bulkDesc": "Select attendance status for",
  "calendar.detail.bulkDescSuffix": "selected students",
  "calendar.detail.reviewedBtn": "Reviewed",
  "calendar.detail.addReview": "Add",
  "calendar.detail.notePlaceholder": "Note...",
  "calendar.detail.noDescription": "No description",
  "calendar.feedback.title": "Teacher Feedback",
  "calendar.feedback.class": "Class",
  "calendar.feedback.criteria": "Criteria evaluation",
  "calendar.feedback.loading": "Loading feedback...",
  "calendar.feedback.empty": "No feedback yet",
  "calendar.feedback.noComment": "No comment",
  "calendar.feedback.thanks": "💙 Thank you for your feedback!",
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "vi",
  setLang: () => {},
  t: (key) => key,
  tNav: (text) => text,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem("app_lang");
    return (stored === "en" || stored === "vi") ? stored : "vi";
  });

  const setLang = (newLang: Language) => {
    localStorage.setItem("app_lang", newLang);
    setLangState(newLang);
  };

  const t = (key: string): string => {
    if (lang === "en") {
      return enCalendar[key] ?? translations["en"][key] ?? translations["vi"][key] ?? key;
    }
    return translations["vi"][key] ?? key;
  };

  const tNav = (viText: string): string => {
    if (lang === "vi") return viText;
    return navMap[viText] ?? viText;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, tNav }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
