apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinodechat-uploads-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: highio-az4
  resources:
    requests:
      storage: 20Gi
