export const donTuTranslations = {
  vi: {
    "mySpace.donTu.title": "Đơn từ của tôi", "mySpace.donTu.personalInfo": "Thông tin cá nhân", "mySpace.donTu.linkedStudents": "Đơn từ của các học viên đã liên kết", "mySpace.donTu.studentRequests": "Đơn từ của học viên", "mySpace.donTu.loadScheduleError": "Không thể tải lịch học",
    "mySpace.donTu.add": "Thêm mới", "mySpace.donTu.loading": "Đang tải dữ liệu...", "mySpace.donTu.loadError": "Không thể tải dữ liệu đơn từ.", "mySpace.donTu.loadingStudent": "Đang nhận diện thông tin học viên...", "mySpace.donTu.studentLoadError": "Không thể tải thông tin học viên và cơ sở được gán.",
    "mySpace.donTu.requests": "Đơn từ", "mySpace.donTu.rewardsPenalties": "Thưởng / Phạt", "mySpace.donTu.advances": "Tạm ứng", "mySpace.donTu.totalRequests": "Tổng số đơn", "mySpace.donTu.pending": "Chờ duyệt", "mySpace.donTu.approved": "Đã duyệt", "mySpace.donTu.rejected": "Từ chối",
    "mySpace.donTu.status": "Trạng thái", "mySpace.donTu.allStatuses": "Tất cả trạng thái", "mySpace.donTu.requestType": "Loại đơn", "mySpace.donTu.allRequestTypes": "Tất cả loại đơn", "mySpace.donTu.student": "Học viên", "mySpace.donTu.allStudents": "Tất cả học viên", "mySpace.donTu.requestCount": "đơn từ", "mySpace.donTu.noMatchingRequests": "Chưa có đơn từ phù hợp",
    "mySpace.donTu.sender": "Người gửi", "mySpace.donTu.time": "Thời gian", "mySpace.donTu.sessions": "Số buổi", "mySpace.donTu.hours": "Số giờ", "mySpace.donTu.reasonNotes": "Lý do / Ghi chú", "mySpace.donTu.session": "buổi", "mySpace.donTu.me": "Tôi",
    "mySpace.donTu.totalReward": "Tổng thưởng", "mySpace.donTu.totalPenalty": "Tổng phạt", "mySpace.donTu.all": "Tất cả", "mySpace.donTu.reward": "Thưởng", "mySpace.donTu.penalty": "Phạt", "mySpace.donTu.noRewards": "Chưa có phiếu thưởng / phạt", "mySpace.donTu.type": "Loại", "mySpace.donTu.date": "Ngày", "mySpace.donTu.amount": "Số tiền", "mySpace.donTu.reason": "Lý do",
    "mySpace.donTu.totalAdvance": "Tổng tạm ứng", "mySpace.donTu.noAdvances": "Chưa có phiếu tạm ứng", "mySpace.donTu.documentDueDate": "Hạn hoàn chứng từ",
    "mySpace.donTu.addStudentLeave": "Thêm đơn xin nghỉ", "mySpace.donTu.assignedLocation": "Cơ sở được gán", "mySpace.donTu.noLocation": "Chưa được gán cơ sở", "mySpace.donTu.leavePeriod": "Thời gian xin nghỉ", "mySpace.donTu.start": "Bắt đầu", "mySpace.donTu.end": "Kết thúc", "mySpace.donTu.actualSchedule": "Lịch học thực tế", "mySpace.donTu.selectedSessions": "Đã chọn {count} buổi", "mySpace.donTu.noSchedules": "Không có lịch học trong khoảng thời gian này.", "mySpace.donTu.chooseTime": "Chọn thời gian để hệ thống tải lịch học thực tế.", "mySpace.donTu.chooseSchedules": "Chọn những buổi học mà học viên muốn xin nghỉ trong khoảng thời gian đã chọn.", "mySpace.donTu.description": "Mô tả", "mySpace.donTu.leaveReasonPlaceholder": "Nhập lý do xin nghỉ...", "mySpace.donTu.cancel": "Hủy", "mySpace.donTu.sendRequest": "Gửi đơn",
    "mySpace.donTu.addRequest": "Thêm đơn mới", "mySpace.donTu.staff": "Nhân sự", "mySpace.donTu.chooseRequestType": "Chọn loại đơn", "mySpace.donTu.fromDate": "Từ ngày", "mySpace.donTu.toDate": "Đến ngày", "mySpace.donTu.fromTime": "Từ giờ", "mySpace.donTu.toTime": "Đến giờ", "mySpace.donTu.reasonPlaceholder": "Nhập lý do...", "mySpace.donTu.createRequest": "Tạo đơn",
    "mySpace.donTu.leave": "Nghỉ phép", "mySpace.donTu.annualLeave": "Nghỉ phép năm", "mySpace.donTu.overtime": "Tăng ca", "mySpace.donTu.studentLeave": "Xin nghỉ học",
    "mySpace.donTu.sentStudentLeave": "Đã gửi đơn xin nghỉ", "mySpace.donTu.sendStudentLeaveError": "Không thể gửi đơn xin nghỉ", "mySpace.donTu.createdLeave": "Đã tạo đơn nghỉ phép", "mySpace.donTu.createLeaveError": "Không thể tạo đơn nghỉ phép", "mySpace.donTu.enterLeavePeriod": "Vui lòng nhập thời gian xin nghỉ", "mySpace.donTu.invalidDateRange": "Ngày bắt đầu không được sau ngày kết thúc", "mySpace.donTu.invalidOvertime": "Thời gian tăng ca không hợp lệ", "mySpace.donTu.chooseSchedule": "Vui lòng chọn ít nhất một lịch học muốn xin nghỉ",
  },
  en: {
    "mySpace.donTu.title": "My Requests", "mySpace.donTu.personalInfo": "Personal information", "mySpace.donTu.linkedStudents": "Requests for linked students", "mySpace.donTu.studentRequests": "Student requests", "mySpace.donTu.loadScheduleError": "Could not load the class schedule",
    "mySpace.donTu.add": "Add new", "mySpace.donTu.loading": "Loading data...", "mySpace.donTu.loadError": "Could not load requests.", "mySpace.donTu.loadingStudent": "Identifying student information...", "mySpace.donTu.studentLoadError": "Could not load student and assigned location information.",
    "mySpace.donTu.requests": "Requests", "mySpace.donTu.rewardsPenalties": "Rewards / Penalties", "mySpace.donTu.advances": "Advances", "mySpace.donTu.totalRequests": "Total requests", "mySpace.donTu.pending": "Pending", "mySpace.donTu.approved": "Approved", "mySpace.donTu.rejected": "Rejected",
    "mySpace.donTu.status": "Status", "mySpace.donTu.allStatuses": "All statuses", "mySpace.donTu.requestType": "Request type", "mySpace.donTu.allRequestTypes": "All request types", "mySpace.donTu.student": "Student", "mySpace.donTu.allStudents": "All students", "mySpace.donTu.requestCount": "requests", "mySpace.donTu.noMatchingRequests": "No matching requests",
    "mySpace.donTu.sender": "Submitted by", "mySpace.donTu.time": "Time", "mySpace.donTu.sessions": "Sessions", "mySpace.donTu.hours": "Hours", "mySpace.donTu.reasonNotes": "Reason / Notes", "mySpace.donTu.session": "sessions", "mySpace.donTu.me": "Me",
    "mySpace.donTu.totalReward": "Total rewards", "mySpace.donTu.totalPenalty": "Total penalties", "mySpace.donTu.all": "All", "mySpace.donTu.reward": "Reward", "mySpace.donTu.penalty": "Penalty", "mySpace.donTu.noRewards": "No reward / penalty records", "mySpace.donTu.type": "Type", "mySpace.donTu.date": "Date", "mySpace.donTu.amount": "Amount", "mySpace.donTu.reason": "Reason",
    "mySpace.donTu.totalAdvance": "Total advances", "mySpace.donTu.noAdvances": "No advance records", "mySpace.donTu.documentDueDate": "Document due date",
    "mySpace.donTu.addStudentLeave": "Add leave request", "mySpace.donTu.assignedLocation": "Assigned location", "mySpace.donTu.noLocation": "No location assigned", "mySpace.donTu.leavePeriod": "Leave period", "mySpace.donTu.start": "Start", "mySpace.donTu.end": "End", "mySpace.donTu.actualSchedule": "Actual schedule", "mySpace.donTu.selectedSessions": "Selected {count} sessions", "mySpace.donTu.noSchedules": "No classes in this period.", "mySpace.donTu.chooseTime": "Choose a period to load the actual schedule.", "mySpace.donTu.chooseSchedules": "Select the classes the student wants to be absent from in the selected period.", "mySpace.donTu.description": "Description", "mySpace.donTu.leaveReasonPlaceholder": "Enter the reason for leave...", "mySpace.donTu.cancel": "Cancel", "mySpace.donTu.sendRequest": "Send request",
    "mySpace.donTu.addRequest": "Add request", "mySpace.donTu.staff": "Staff", "mySpace.donTu.chooseRequestType": "Choose request type", "mySpace.donTu.fromDate": "From date", "mySpace.donTu.toDate": "To date", "mySpace.donTu.fromTime": "From time", "mySpace.donTu.toTime": "To time", "mySpace.donTu.reasonPlaceholder": "Enter reason...", "mySpace.donTu.createRequest": "Create request",
    "mySpace.donTu.leave": "Leave", "mySpace.donTu.annualLeave": "Annual leave", "mySpace.donTu.overtime": "Overtime", "mySpace.donTu.studentLeave": "Student leave",
    "mySpace.donTu.sentStudentLeave": "Leave request sent", "mySpace.donTu.sendStudentLeaveError": "Could not send leave request", "mySpace.donTu.createdLeave": "Leave request created", "mySpace.donTu.createLeaveError": "Could not create leave request", "mySpace.donTu.enterLeavePeriod": "Please enter the leave period", "mySpace.donTu.invalidDateRange": "Start date cannot be after end date", "mySpace.donTu.invalidOvertime": "Invalid overtime period", "mySpace.donTu.chooseSchedule": "Please select at least one class to request leave from",
  },
} as const;

export type DonTuTranslationKey = keyof typeof donTuTranslations.vi;