// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bang-tin/CardGrid.tsx": () => import("../components/mockups/bang-tin/CardGrid.tsx"),
  "./components/mockups/bang-tin/Magazine.tsx": () => import("../components/mockups/bang-tin/Magazine.tsx"),
  "./components/mockups/calendar-responsive/Current.tsx": () => import("../components/mockups/calendar-responsive/Current.tsx")
};
